// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"wire-interface/internal/conf"
	"wire-interface/internal/controller"
	"wire-interface/internal/dao"
	"wire-interface/internal/model"
	"wire-interface/internal/service"
)

// Injectors from wire.go:

func InitCtrl() *controller.UserController {
	user := _wireUserValue
	db := conf.NewGorm(user)
	userDao := &dao.UserDao{
		Db: db,
	}
	userService := service.UserService{
		UserDao: userDao,
	}
	userController := &controller.UserController{
		UserService: userService,
	}
	return userController
}

var (
	_wireUserValue = &model.User{
		Name: "dgsdg124",
	}
)
