// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"wire-base-use/internal/conf"
	"wire-base-use/internal/controller"
	"wire-base-use/internal/dao"
	"wire-base-use/internal/service"
)

// Injectors from wire.go:

func InitCtrl() *controller.UserController {
	db := conf.NewGorm()
	userDao := dao.NewUserDao(db)
	userService := service.NewUserService(userDao)
	userController := controller.NewUserController(userService)
	return userController
}
