// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gin-wire/internal/conf"
	"gin-wire/internal/controller"
	"gin-wire/internal/dao"
	"gin-wire/internal/service"
)

// Injectors from wire.go:

func wireApp() *conf.HttpServer {
	logger := conf.NewZap()
	engine := conf.NewGin(logger)
	db := conf.NewGorm()
	userDao := &dao.UserDao{
		Db: db,
	}
	userService := service.UserService{
		UserDao: userDao,
	}
	userController := controller.NewUserController(engine, userService, logger)
	httpServer := &conf.HttpServer{
		Logger:  logger,
		Engine:  engine,
		UserCtl: userController,
	}
	return httpServer
}
